server:
  port: 7083
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://139.9.60.208:8081/xxl-job-admin
    executor:
      appname: kettle-web
      ip: ''
      logpath: /home/kettle/log/
      logretentiondays: -1
      port: 2001
spring:
  jobPath: /home/kettle/job/ucg-etl/
  pluginPath: /home/kettle/plugin
  jdbcPath: /home/kettle/jdbc


logging:
  path: /home/kettle/logs/kettle

mail:
  username: system@join-share.co
  password: ucg_123456
  sender: system@join-share.com
  host: smtp.chengmail.cn"
  port: 25
  address: luoxianze@join-share.com
